#!/usr/bin/env bash
# configure LE to haproxy
# to test our configuration changes by calling
#   the haproxy executable with the "-c"parameter, such as:
#     haproxy -c -f /etc/hapee-1.8/hapee-lb.cfg

global
  # global settings here
  maxconn 50000
  log /dev/log local0
  user haproxy
  group haproxy
  stats socket /run/haproxy/admin.sock user haproxy group haproxy
  nbproc 2
  nbthread 4
  cpu-map auto:1/1-4 0-3
  daemons
  
defaults
  # defaults here
  timeout connect 10s
  timeout client 30s
  timeout server 30s
  log global
  mode http
  option httplog
  macconn 3000

frontend
  # a frontend that accepts request from clients
  bind IP:port
  bind IP:port ssl crt /etc/ssl/certs/theancientwhispers.tech
  http-request redirect sheme https unless { ssl_fc }
  use_backend api_servers if {path_beg /api/ }
  default_backend web_servers

backend
  # servers that fulfill the requests
