#!/usr/bin/env bash
#Setup, default path, restart when making configurations updates and -y to auto
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
