#!/usr/bin/env bash
#seq for iterate in a range
for i in $(seq 1 20); do
  if ! (( i % 15)); then
    echo FizzBuzz
  elif ! (( i % 5 )); then
    echo Buzz
  elif ! (( i % 3 )); then
    echo Fizz
  else
    echo "$i"
  fi
done
