#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd
FILE="etc/passwd"
while IFS=: read -r username userid groupid homedir cmdshell password comment
do
  echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $comment"
done < $FILE
