#!/usr/bin/env bash
#bash script to display numbers from 1 ot 20
# and add string to number 4, 9, and 17
n=1

while [ $n -lt '21' ]
do 
  echo "$n"
  ((n++))
case $n in

  "5")
    echo "bad luck from China"
    ;;

  "10")
    echo "bad luck from Japan"
    ;;

  "18")
    echo "bad luck from Italy"
    ;;
esac
done
