#!/usr/bin/env bash
#display minutes but, in one hour display a string with counter
m=1
h=0

while [ $h -le '12' ]
do
  echo "Hour = $h"
  while [ $m -lt 60 ]
  do
    echo "$m"
    ((m++))
  done
  ((h++))
done
