#!/usr/bin/env bash
#display minutes but, in one hour display a string with counter
m=1
h=0

while [ $h -lt '13' ];
do
  echo "Hour: $h"
  m=1
  while [ $m -lt 60 ];
  do
    echo "$m"
    ((m++))
  done
  ((h++))
done
