#!/usr/bin/env bash
Host 4394-web-01
      HostName 35.173.129.145
      Port 22
      User ubuntu
      IdentityFile ~/.ssh/school
      IdentityFile ~/.ssh/known_hosts
      PasswordAuthentication no
